@extends('layouts.master')

@section('content')
    @include('partials/static_links_nav')

    <section class="static_page_sec privacy_sec">

        <div class="container more">
            <div class="row">
                <div class="col-xs-12">

                    <div class="well padding-md">
                        <h3 class="normal_header">Privacy Policy</h3>
                    </div> <!-- well ends -->

                    <div class="static_content col-xs-12">
                        <div class="main col-xs-12 col-md-9">
                            <p>This policy explains how we, Bueno, a brand of <a href="http://www.bueno.kitchen" target="_blank">http://www.bueno.kitchen</a>, use your personal information which you provide to us when using our services.</p>

                            <h4>WHAT INFORMATION WE COLLECT ABOUT YOU?</h4>
                            <p>We collect personal information from you when you order goods or services from us or use our website. We also collect information when you complete any customer survey. Website usage information may also be collected using cookies.</p>

                            <h4>COOKIES AND GOOGLE ANALYTICS</h4>
                            <p>Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site.</p>

                            <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files saved on your computer, to help the website analyze how you use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. If this website anonymizes IP addresses, your IP address will be truncated by Google within an EU member state or other EEA state before being transmitted to the US. Only in exceptional situations will your full IP address be transmitted to Google servers in the United States and truncated there. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. You can also prevent Google from collecting information (including your IP address) via cookies and processing this information by downloading this browser plug-in and installing it: <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">https://tools.google.com/dlpage/gaoptout</a></p>

                            <p>Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit www.allaboutcookies.org.</p>

                            <h4>HOW WILL WE USE THE INFORMATION WE COLLECT FROM YOU?</h4>
                            <p>Information that we collect from you is used to process your order and to manage your account. We may also use your information to email / SMS you about other products or services that we think may be of interest to you.</p>

                            <p>In processing your order we may send your information to credit reference and fraud prevention agencies.</p>

                            <h4>ACCESS TO YOUR INFORMATION</h4>
                            <p>You have a right to request a copy of the information we hold on you at any time. Please email us if you would like to receive a copy of this information – <a href="mailto:bueno@bueno.co.in" target="_blank">bueno@bueno.co.in</a>. There will be a small charge for processing this request.</p>
                        </div> <!-- main ends -->
                    </div> <!-- static_content ends -->

                </div> <!-- col-xs-12 ends -->
            </div> <!-- row ends -->
        </div> <!-- container ends -->

    </section> <!-- <section> ends -->


@stop